# fly.toml app configuration file generated for painting-bot on 2023-10-21T14:15:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "painting-bot"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
