# fly.toml app configuration file generated for painting-bot on 2023-10-21T14:15:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "painting-bot"
primary_region = "yyz"

[build]

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = false  # prevent automatic suspension
  min_machines_running = 1  # keep a machine running at all times